version: 0.1
phases:
  pre_build:
    commands:
      - "curl -X POST --data-urlencode \"payload={\\\"channel\\\": \\\"#ops-debug\\\", \\\"text\\\": \\\"radio.radiotopia.fm – Starting S3 sync to bucket: $STATIC_SITE_BUCKET\\\"}\" $SLACK_WEBHOOK_URL"
  build:
    commands:
      - echo Starting S3 sync to $STATIC_SITE_BUCKET
      - aws s3 sync . s3://$STATIC_SITE_BUCKET --acl private --region $AWS_REGION --delete --exclude ".git/*" --exclude "buildspec.yml"
artifacts:
  files:
    - index.html
