version: 0.1
phases:
  install:
    commands:
      - echo Install phase `date`
  pre_build:
    commands:
      - echo Pre-build phase `date`
  build:
    commands:
      - echo Build phase `date`
      - aws s3 sync . s3://$STATIC_SITE_BUCKET --acl private --region $AWS_REGION --delete --exclude ".git/*"
  post_build:
    commands:
      - echo Post-build phase `date`
artifacts:
  files:
    - index.html
